name: Firewall Assignment Autograding

on:
  push:
  workflow_dispatch:

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Give test script permission
        run: chmod +x test.sh

      - name: Run firewall tests
        run: ./test.sh
